# THE PARAMETERS OF THIS FILE ARE USED IF THE CORRESPONDING VALUE IS NOT DECLARED IN THE OTHER CONFIG!
seed: 0
method: InstantUV
experiment:
  name: Default
  split: human
  description: Default Config for human

data:
  raw_data_path: data/raw/human_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/human_dataset_v2_tiny/
  mesh_path: data/raw/human/RUST_3d_Low1.obj
  img_height: 512
  img_width: 512
  data_split: config/human/data_split.yaml
  train_render_img_names:
    - human000

  render_img_directory: reports/

preprocessing:
  export_angles: false
  export_coords3d: false

  uv_backend: gt
  uv_backend_options:
    xatlas: # TODO: Integrate these, for now just draft
      padding: 4
    blender:
      padding: 4

model:
  loss: "L1"
  seam_loss: -1  # Negative values <=> Seam loss not used

  # TNN CONFIG
  n_input_dims: 2
  n_output_dims: 3
  encoding:
    otype: "HashGrid"
    n_levels: 30
    n_features_per_level: 4
    log2_hashmap_size: 18
    base_resolution: 16
    per_level_scale: 1.26
  network:
    otype: "FullyFusedMLP"
    activation: "ReLU"
    output_activation: "Sigmoid"
    n_neurons: 64
    n_hidden_layers: 3


training:
  device: AUTO

  epochs: 101
  eval_every: 10
  checkpoint_every: 20
  batch_size: 4000
  batch_size_val: 262144
  render_scale: 1  # TODO: Probably deprecated this does not improve anything
  save_validation_images: false
  save_uvs: true

  lr: 1e-2
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-08
  weight_decay: 0

  use_wandb: false
