seed: 0
method: InstantUV
experiment:
  name: XATLAS Human
  split: human
  description: XATLAS Config for human
data:
  raw_data_path: data/raw/human_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/human_dataset_v2_tiny/xatlas
  mesh_path: DEFAULT
  img_height: DEFAULT
  img_width: DEFAULT
  data_split: DEFAULT
  train_render_img_names: DEFAULT

  render_img_directory: reports/xatlas

preprocessing:
  export_angles: false
  export_coords3d: false

  uv_backend: xatlas
  uv_backend_options:
    xatlas:
      padding: 6

model:
  loss: DEFAULT

training:
  epochs: DEFAULT
  eval_every: DEFAULT
  checkpoint_every: DEFAULT
  batch_size: DEFAULT
  render_scale: DEFAULT  # TODO: Probably deprecated this does not improve anything
  save_validation_images: false

  lr: DEFAULT
  beta1: DEFAULT
  beta2: DEFAULT
  epsilon: DEFAULT
  weight_decay: DEFAULT


