seed: 0
method: InstantUV 
experiment:
  name: Default
  split: human
  description: Default Config for human
data:
  raw_data_path: data/raw/human_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/human_dataset_v2_tiny/
  mesh_path: data/raw/human/RUST_3d_Low1.obj
  img_height: 512
  img_width: 512
  data_split: config/human/data_split.yaml
  train_render_img_names:
    - human000

  render_img_directory: reports/
model:
  loss: "L1"  # zu training oder model? FIXME training would be better imo
  # TODO model config

training:
  lr: 1e-3
  weight_decay: 5e-5
  epochs: 300
  eval_every: 2
  checkpoint_every: 20
  batch_size: 4000 # 65536  # 2**16