seed: 0
method: InstantUV
experiment:
  name: Default
  split: cat
  description: Default Config for cat
data:
  raw_data_path: data/raw/cat_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/cat_dataset_v2_tiny/
  # mesh_path: data/raw/cat_rescaled_rotated/12221_Cat_v1_l3.obj
  mesh_path: data/preprocessed/triangle_CAT.obj
  img_height: 512
  img_width: 512
  data_split: config/cat/data_split.yaml
  train_render_img_names:
    - cat000

  render_img_directory: reports/

# COPIED!!!
model:
  loss: "L1"  # zu training oder model?
  # TODO model config

training:
  epochs: 2000
  eval_every: 10
  checkpoint_every: 20
  batch_size: 1000
  render_scale: 1
  save_validation_images: false
  uv_backend: xatlas

  uv_backend_options:  # TODO: Hier oder wo anders
    xatlas: # TODO: Integrate these, for now just draft
      padding: 4
    blender:
      padding: 4