seed: 0
method: InstantUV
experiment:
  name: Default
  split: cat
  description: Default Config for cat
data:
  raw_data_path: data/raw/cat_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/cat_dataset_v2_tiny/
  mesh_path: data/raw/cat_rescaled_rotated/12221_Cat_v1_l3.obj
  img_height: 512
  img_width: 512
  data_split: config/experiments/cat/data_split.yaml

  train_render_img_names:
    - cat000

  render_img_directory: reports/
model:
  # TODO model config 
training:
  # TODO training config